body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: "To Reproduce:"
      description: Steps to reproduce the behavior
      placeholder: Steps to reproduce the behavior
      value: "A bug happened!"
    validations:
      required: true    
  - type: dropdown
    id: ha_version
    attributes:
      label: HA Version
      description: What version of HA are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: card_version
    attributes:
      label: Card Version
      description: What version of the card are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - HA App on Android
        - HA App on iOS
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree that ii updated HA and the card to the latest version and deleted my cache.
          required: true



**Screenshots**
If applicable, add screenshots to help explain your problem.


