name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels:
- bug
assignees:
- xBourner
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this bug report!

      '
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  id: to-reproduce
  attributes:
    label: 'To Reproduce:'
    description: Steps to reproduce the behavior
    placeholder: Steps to reproduce the behavior
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: If applicable, add screenshots to help explain your problem.
- type: dropdown
  id: ha_version
  attributes:
    label: HA Version
    description: What version of HA are you running?
    options: []
    default: 0
  validations:
    required: true
- type: dropdown
  id: card_version
  attributes:
    label: Card Version
    description: What version of the card are you running?
    options:
    - 3.0.3-beta
    - 3.0.3
    - 3.0.2-beta
    - 3.0.2
    - 3.0.1-beta
    - 3.0.1
    - '3.0'
    - 3-beta
    - 2.13.3-beta
    - 2.13.2-beta
    - 2.13.1-beta
    - 2.13-beta
    - 2.12.2
    - 2.12.1
    - '2.12'
    - '2.11'
    - 2.10.3
    - 2.10.2
    - 2.10.1
    - '2.10'
    - 2.9.1
    - 2.9.0
    - 2.8.4
    - 2.8.3
    - 2.8.2
    - 2.8.1
    - 2.8.0
    - 2.7.2
    - 2.7.1
    - 2.7.0
    - 2.6.3
    - 2.6.2
    - 2.6.1
    - '2.6'
    - '2.5'
    - 2.4.3
    - 2.4.2
    - 2.4.1
    - 2.4.0
    - 2.3.1
    - 2.3.0
    - 2.2.1
    - 2.2.0
    - 2.1.2
    - 2.1.1
    - 2.1.0
    - '2.0'
    - 1.2.1
    - 1.2.0
    - 1.1.1
    - 1.1.0
    default: 0
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
    - HA App on Android
    - HA App on iOS
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
    options:
    - label: I agree that ii updated HA and the card to the latest version and deleted
        my cache.
      required: true
