import {
  mdiAlarmLight,
  mdiAlarmLightOff,
  mdiBellRing,
  mdiBellOff,
  mdiLockOpen,
  mdiLock,
  mdiLightbulb,
  mdiLightbulbOff,
  mdiCast,
  mdiCastOff,
  mdiThermostat,
  mdiThermostatCog,
  mdiAirHumidifier,
  mdiAirHumidifierOff,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiPowerPlug,
  mdiPowerPlugOff,
  mdiRobotVacuum,
  mdiRobotVacuumOff,
  mdiRobotMower,
  mdiFan,
  mdiFanOff,
  mdiGarageOpen,
  mdiGarage,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiGateOpen,
  mdiGate,
  mdiBlindsOpen,
  mdiBlinds,
  mdiCurtains,
  mdiCurtainsClosed,
  mdiValveOpen,
  mdiValveClosed,
  mdiAwningOutline,
  mdiWindowShutterOpen,
  mdiWindowShutter,
  mdiRollerShade,
  mdiRollerShadeClosed,
  mdiWindowOpen,
  mdiWindowClosed,
  mdiPowerOff,
  mdiMotionSensor,
  mdiMotionSensorOff,
  mdiWaterAlert,
  mdiWaterOff,
  mdiHomeOutline,
  mdiHomeExportOutline,
  mdiSeat,
  mdiSeatOutline,
  mdiVibrate,
  mdiVibrateOff,
  mdiShieldLockOpen,
  mdiShieldLock,
  mdiAlertCircleOutline,
  mdiAlertCircleCheckOutline,
  mdiSmokeDetectorOutline,
  mdiSmokeDetectorOffOutline,
  mdiPlay,
  mdiPause,
  mdiPower,
  mdiBatteryAlert,
  mdiBattery,
  mdiBatteryCharging,
  mdiBatteryCheck,
  mdiGasStationOutline,
  mdiGasStationOffOutline,
  mdiMoleculeCo,
  mdiSnowflake,
  mdiSnowflakeOff,
  mdiWeatherSunny,
  mdiWeatherSunnyOff,
  mdiConnection,
  mdiShieldAlertOutline,
  mdiShieldCheckOutline,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiAutorenew,
  mdiAutorenewOff,
  mdiShieldHome,
  mdiLightbulbOutline,
  mdiLightbulbOffOutline,
  mdiCar,
  mdiCarOff,
  mdiAccount,
  mdiAccountOff,
  mdiValve,
  mdiWaterBoiler,
  mdiWaterPumpOff,
  mdiRemote,
  mdiRemoteOff,
  mdiAirFilter,
  mdiCamera,
  mdiCameraOff,
  mdiCalendar,
  mdiCalendarRemove,
  mdiMovie,
  mdiMovieOff,
  mdiBell,
  mdiGauge,
  mdiScriptText,
  mdiTagMultiple,
  mdiFormatListBulleted,
  mdiRobot,
  mdiRobotOff,
  mdiGestureTapButton,
  mdiNumeric,
  mdiCommentMultiple,
  mdiSatelliteVariant,
  mdiCounter,
  mdiCalendarStar,
  mdiGoogleCirclesCommunities,
  mdiImage,
  mdiImageOff,
  mdiImageFilterCenterFocus,
  mdiCalendarClock,
  mdiTextBox,
  mdiRecordRec,
  mdiRecord,
  mdiWeatherNight,
  mdiClockOutline,
  mdiClockTimeEightOutline,
  mdiTimerOutline,
  mdiTimerOff,
  mdiCheckCircleOutline,
  mdiCheckboxBlankCircleOutline,
  mdiMicrophone,
  mdiMicrophoneOff,
  mdiWeatherPartlyCloudy,
  mdiMapMarker,
  mdiMapMarkerOff,
} from "@mdi/js";
import { DomainIconDef, DomainFeatureDef } from "./ha/types";


export const DOMAIN_ICONS: Record<string, DomainIconDef> = {
  alarm_control_panel: { on: mdiAlarmLight, off: mdiAlarmLightOff },
  siren: { on: mdiBellRing, off: mdiBellOff },
  lock: { on: mdiLockOpen, off: mdiLock },
  light: { on: mdiLightbulb, off: mdiLightbulbOff },
  media_player: { on: mdiCast, off: mdiCastOff },
  climate: { on: mdiThermostat, off: mdiThermostatCog },
  humidifier: { on: mdiAirHumidifier, off: mdiAirHumidifierOff },
  switch: {
    on: mdiToggleSwitch,
    off: mdiToggleSwitchOff,
    switch: { on: mdiToggleSwitch, off: mdiToggleSwitchOff },
    outlet: { on: mdiPowerPlug, off: mdiPowerPlugOff },
  },
  vacuum: { on: mdiRobotVacuum, off: mdiRobotVacuumOff },
  lawn_mower: { on: mdiRobotMower, off: mdiRobotMower },
  fan: { on: mdiFan, off: mdiFanOff },

  cover: {
    on: mdiGarageOpen,
    off: mdiGarage,
    garage: { on: mdiGarageOpen, off: mdiGarage },
    door: { on: mdiDoorOpen, off: mdiDoorClosed },
    gate: { on: mdiGateOpen, off: mdiGate },
    blind: { on: mdiBlindsOpen, off: mdiBlinds },
    curtain: { on: mdiCurtains, off: mdiCurtainsClosed },
    damper: { on: mdiValveOpen, off: mdiValveClosed },
    awning: { on: mdiAwningOutline, off: mdiAwningOutline },
    shutter: { on: mdiWindowShutterOpen, off: mdiWindowShutter },
    shade: { on: mdiRollerShade, off: mdiRollerShadeClosed },
    window: { on: mdiWindowOpen, off: mdiWindowClosed },
  },
  binary_sensor: {
    on: mdiPowerOff,
    off: mdiPowerOff,
    motion: { on: mdiMotionSensor, off: mdiMotionSensorOff },
    moisture: { on: mdiWaterAlert, off: mdiWaterOff },
    window: { on: mdiWindowOpen, off: mdiWindowClosed },
    door: { on: mdiDoorOpen, off: mdiDoorClosed },
    lock: { on: mdiLockOpen, off: mdiLock },
    presence: { on: mdiHomeOutline, off: mdiHomeExportOutline },
    occupancy: { on: mdiSeat, off: mdiSeatOutline },
    vibration: { on: mdiVibrate, off: mdiVibrateOff },
    opening: { on: mdiShieldLockOpen, off: mdiShieldLock },
    garage_door: { on: mdiGarageOpen, off: mdiGarage },
    problem: {
      on: mdiAlertCircleOutline,
      off: mdiAlertCircleCheckOutline,
    },
    smoke: {
      on: mdiSmokeDetectorOutline,
      off: mdiSmokeDetectorOffOutline,
    },
    running: { on: mdiPlay, off: mdiPause },
    plug: { on: mdiPowerPlug, off: mdiPowerPlugOff },
    power: { on: mdiPower, off: mdiPowerOff },
    battery: { on: mdiBatteryAlert, off: mdiBattery },
    battery_charging: { on: mdiBatteryCharging, off: mdiBatteryCheck },
    gas: { on: mdiGasStationOutline, off: mdiGasStationOffOutline },
    carbon_monoxide: { on: mdiMoleculeCo, off: mdiMoleculeCo },
    cold: { on: mdiSnowflake, off: mdiSnowflakeOff },
    heat: { on: mdiWeatherSunny, off: mdiWeatherSunnyOff },
    connectivity: { on: mdiConnection, off: mdiConnection },
    safety: { on: mdiShieldAlertOutline, off: mdiShieldCheckOutline },
    sound: { on: mdiVolumeHigh, off: mdiVolumeOff },
    update: { on: mdiAutorenew, off: mdiAutorenewOff },
    tamper: { on: mdiShieldHome, off: mdiShieldHome },
    light: { on: mdiLightbulbOutline, off: mdiLightbulbOffOutline },
    moving: { on: mdiCar, off: mdiCarOff },
  },
  person: { on: mdiAccount, off: mdiAccountOff },
  device_tracker: { on: mdiAccount, off: mdiAccountOff },
  valve: { on: mdiValve, off: mdiValveClosed },
  water_heater: { on: mdiWaterBoiler, off: mdiWaterPumpOff },
  remote: { on: mdiRemote, off: mdiRemoteOff },
  update: { on: mdiAutorenew, off: mdiAutorenewOff },
  air_quality: { on: mdiAirFilter, off: mdiAirFilter },
  camera: { on: mdiCamera, off: mdiCameraOff },
  calendar: { on: mdiCalendar, off: mdiCalendarRemove },
  scene: { on: mdiMovie, off: mdiMovieOff },
  notifications: { on: mdiBell, off: mdiBellOff },
  sensor: { on: mdiGauge, off: mdiGauge },
  script: { on: mdiScriptText, off: mdiScriptText },
  tags: { on: mdiTagMultiple, off: mdiTagMultiple },
  select: { on: mdiFormatListBulleted, off: mdiFormatListBulleted },
  automation: { on: mdiRobot, off: mdiRobotOff },
  button: { on: mdiGestureTapButton, off: mdiGestureTapButton },
  number: { on: mdiNumeric, off: mdiNumeric },
  conversation: { on: mdiCommentMultiple, off: mdiCommentMultiple },
  assist_satellite: {
    on: mdiSatelliteVariant,
    off: mdiSatelliteVariant,
  },
  counter: { on: mdiCounter, off: mdiCounter },
  event: { on: mdiCalendarStar, off: mdiCalendarStar },
  group: {
    on: mdiGoogleCirclesCommunities,
    off: mdiGoogleCirclesCommunities,
  },
  image: { on: mdiImage, off: mdiImageOff },
  image_processing: {
    on: mdiImageFilterCenterFocus,
    off: mdiImageFilterCenterFocus,
  },
  input_boolean: { on: mdiToggleSwitch, off: mdiToggleSwitchOff },
  input_datetime: { on: mdiCalendarClock, off: mdiCalendarClock },
  input_number: { on: mdiNumeric, off: mdiNumeric },
  input_select: {
    on: mdiFormatListBulleted,
    off: mdiFormatListBulleted,
  },
  input_text: { on: mdiTextBox, off: mdiTextBox },
  stt: { on: mdiRecordRec, off: mdiRecord },
  sun: { on: mdiWeatherSunny, off: mdiWeatherNight },
  text: { on: mdiTextBox, off: mdiTextBox },
  date: { on: mdiCalendar, off: mdiCalendarRemove },
  datetime: { on: mdiCalendarClock, off: mdiCalendarClock },
  time: { on: mdiClockOutline, off: mdiClockTimeEightOutline },
  timer: { on: mdiTimerOutline, off: mdiTimerOff },
  todo: {
    on: mdiCheckCircleOutline,
    off: mdiCheckboxBlankCircleOutline,
  },
  tts: { on: mdiVolumeHigh, off: mdiVolumeOff },
  wake_word: { on: mdiMicrophone, off: mdiMicrophoneOff },
  weather: { on: mdiWeatherPartlyCloudy, off: mdiWeatherNight },
  zone: { on: mdiMapMarker, off: mdiMapMarkerOff },
  geo_location: { on: mdiMapMarker, off: mdiMapMarkerOff },
};

export const ALLOWED_DOMAINS = [
  "alarm_control_panel",
  "siren",
  "lock",
  "light",
  "media_player",
  "climate",
  "switch",
  "vacuum",
  "fan",
  "cover",
  "binary_sensor",
  "humidifier",
  "lawn_mower",
  "valve",
  "water_heater",
  "remote",
  "update",
  "device_tracker",
  "input_boolean",
  "timer",
  "counter",
  "calendar",
];

export const TOGGLEABLE_DOMAINS = [
  "light",
  "switch",
  "fan",
  "cover",
  "siren",
  "climate",
  "humidifier",
  "valve",
  "remote",
];

export const OPENABLE_DEVICE_CLASSES = [
  "window",
  "door",
  "lock",
  "awning",
  "blind",
  "curtain",
  "damper",
  "garage",
  "gate",
  "shade",
  "shutter",
];

export const deviceClasses: Record<string, string[]> = {
  binary_sensor: [
    "door",
    "window",
    "lock",
    "motion",
    "presence",
    "occupancy",
    "plug",
    "power",
    "battery",
    "battery_charging",
    "moving",
    "running",
    "gas",
    "carbon_monoxide",
    "vibration",
    "cold",
    "heat",
    "moisture",
    "connectivity",
    "opening",
    "garage_door",
    "light",
    "problem",
    "safety",
    "smoke",
    "sound",
    "tamper",
    "update",
  ],
  cover: [
    "door",
    "window",
    "garage",
    "gate",
    "blind",
    "curtain",
    "damper",
    "awning",
    "shade",
    "shutter",
  ],
  switch: ["switch", "outlet"],
};



export const DOMAIN_FEATURES: Record<string, DomainFeatureDef> = {
    alarm_control_panel: {
      state_content: ["state", "last_changed"],
      features: [
        {
          type: "alarm-modes",
          modes: [
            "armed_home",
            "armed_away",
            "armed_night",
            "armed_vacation",
            "armed_custom_bypass",
            "disarmed",
          ],
        },
      ],
    },
    light: {
      state_content: ["state", "brightness", "last_changed"],
      features: [{ type: "light-brightness" }],
    },
    cover: {
      state_content: ["state", "position", "last_changed"],
      features: [{ type: "cover-open-close" }, { type: "cover-position" }],
    },
    vacuum: {
      state_content: ["state", "last_changed"],
      features: [
        {
          type: "vacuum-commands",
          commands: [
            "start_pause",
            "stop",
            "clean_spot",
            "locate",
            "return_home",
          ],
        },
      ],
    },
    climate: {
      state_content: ["state", "current_temperature", "last_changed"],
      features: [
        {
          type: "climate-hvac-modes",
          hvac_modes: [
            "auto",
            "heat_cool",
            "heat",
            "cool",
            "dry",
            "fan_only",
            "off",
          ],
        },
      ],
    },
    water_heater: {
      state_content: ["state", "last_changed"],
      features: [
        {
          type: "water-heater-operation-modes",
          operation_modes: [
            "electric",
            "gas",
            "heat_pump",
            "eco",
            "performance",
            "high_demand",
            "off",
          ],
        },
      ],
    },
    humidifier: {
      state_content: ["state", "current_humidity", "last_changed"],
      features: [{ type: "target-humidity" }],
    },
    media_player: {
      show_entity_picture: true,
      state_content: ["state", "volume_level", "last_changed"],
      features: [{ type: "media-player-playback" }],
    },
    lock: {
      state_content: ["state", "last_changed"],
      features: [{ type: "lock-commands" }],
    },
    fan: {
      state_content: ["state", "percentage", "last_changed"],
      features: [{ type: "fan-speed" }],
    },
    counter: {
      state_content: ["state", "last_changed"],
      features: [
        {
          type: "counter-actions",
          actions: ["increment", "decrement", "reset"],
        },
      ],
    },
    lawn_mower: {
      state_content: ["state", "last_changed"],
      features: [
        {
          type: "lawn-mower-commands",
          commands: ["start_pause", "dock"],
        },
      ],
    },
    update: {
      state_content: ["state", "latest_version", "last_changed"],
      features: [{ type: "update-actions", backup: "ask" }],
    },
    switch: {
      state_content: ["state", "last_changed"],
      features: [{ type: "toggle" }],
    },
    input_boolean: {
      state_content: ["state", "last_changed"],
      features: [{ type: "toggle" }],
    },
    calendar: {
      state_content: "message",
    },
    timer: {
      state_content: ["state", "remaining_time"],
    },
    binary_sensor: {
      state_content: ["state", "last_changed"],
    },
    device_tracker: {
      state_content: ["state", "last_changed"],
    },
    remote: {
      state_content: ["state", "last_changed"],
    },
    valve: {
      state_content: ["state", "last_changed"],
      features: [{ type: "valve-open-close" }],
    },
  };
