export function initializeEntityConfig() {
    const entityConfig = {
      alarm_control_panel: { icon: 'mdi:bell-ring', sortOrder: 1 },
      siren: { icon: 'mdi:alarm-light', sortOrder: 2 },
      lock: { icon: 'mdi:lock', sortOrder: 3 },  
      light: { icon: 'mdi:lightbulb', sortOrder: 4 },
      media_player: { icon: 'mdi:cast', sortOrder: 5 },
      climate: { icon: 'mdi:thermostat', sortOrder: 6 },
      switch: { icon: 'mdi:power', sortOrder: 7 },
      vacuum: { icon: 'mdi:robot-vacuum', sortOrder: 8 },     
      fan: { icon: 'mdi:fan', sortOrder: 9 },
      humidifier: { icon: 'mdi:air-humidifier', sortOrder: 10 },
      lawn_mower: { icon: 'mdi:robot-mower', sortOrder: 11 },
      valve: { icon: 'mdi:valve', sortOrder: 12 },
      water_heater: { icon: 'mdi:water-boiler', sortOrder: 13 },      	  
      remote: { icon: 'mdi:remote', sortOrder: 14 },	    
      update: { icon: 'mdi:update', sortOrder: 53 },
      device_tracker: { icon: 'mdi:cellphone', sortOrder: 54 },
      input_boolean: { icon: 'mdi:toggle-switch', sortOrder: 55 },
      timer: { icon: 'mdi:timer-outline', sortOrder: 56 },
      counter: { icon: 'mdi:counter', sortOrder: 57 },
      calendar: { icon: 'mdi:calendar', sortOrder: 58 },
      cover: {
        deviceClasses: [
          { name: 'door', icon: 'mdi:door-open', sortOrder: 15 },
          { name: 'window', icon: 'mdi:window-open', sortOrder: 16 },     
          { name: 'garage', icon: 'mdi:garage-open', sortOrder: 17 },
          { name: 'gate', icon: 'mdi:gate-open', sortOrder: 18 },    
          { name: 'blind', icon: 'mdi:blinds-open', sortOrder: 19 },
          { name: 'curtain', icon: 'mdi:curtains', sortOrder: 20 },
          { name: 'damper', icon: 'mdi:valve', sortOrder: 21 },
          { name: 'awning', icon: 'mdi:window-shutter-open', sortOrder: 22 },
          { name: 'shade', icon: 'mdi:roller-shade', sortOrder: 23 },
          { name: 'shutter', icon: 'mdi:window-shutter-open', sortOrder: 24 },
        ],
        icon: 'mdi:alert-circle'
      },
      binary_sensor: {
        deviceClasses: [
          { name: 'door', icon: 'mdi:door-open', sortOrder: 25 },
          { name: 'window', icon: 'mdi:window-open', sortOrder: 26 },
          { name: 'lock', icon: 'mdi:lock-open', sortOrder: 27 },
          { name: 'motion', icon: 'mdi:run', sortOrder: 28 },
          { name: 'presence', icon: 'mdi:home', sortOrder: 29 },
          { name: 'occupancy', icon: 'mdi:seat', sortOrder: 30 },
          { name: 'vibration', icon: 'mdi:vibrate', sortOrder: 31 },
          { name: 'plug', icon: 'mdi:power-plug', sortOrder: 32 },
          { name: 'power', icon: 'mdi:power-plug', sortOrder: 33 },
          { name: 'battery', icon: 'mdi:battery-alert', sortOrder: 34 },
          { name: 'battery_charging', icon: 'mdi:battery-charging', sortOrder: 35 },
          { name: 'moving', icon: 'mdi:car', sortOrder: 36 },
          { name: 'running', icon: 'mdi:play', sortOrder: 37 },
          { name: 'gas', icon: 'mdi:gas-cylinder', sortOrder: 38 },
          { name: 'carbon_monoxide', icon: 'mdi:molecule-co', sortOrder: 39 },
          { name: 'cold', icon: 'mdi:snowflake', sortOrder: 40 },
          { name: 'heat', icon: 'mdi:thermometer', sortOrder: 41 },
          { name: 'moisture', icon: 'mdi:water', sortOrder: 42 },
          { name: 'connectivity', icon: 'mdi:connection', sortOrder: 43 },
          { name: 'opening', icon: 'mdi:door-open', sortOrder: 44 },
          { name: 'garage_door', icon: 'mdi:garage-open', sortOrder: 45 },
          { name: 'light', icon: 'mdi:brightness-5', sortOrder: 46 },
          { name: 'problem', icon: 'mdi:alert-circle', sortOrder: 47 },
          { name: 'safety', icon: 'mdi:shield-alert', sortOrder: 48 },
          { name: 'smoke', icon: 'mdi:smoke-detector', sortOrder: 49 },
          { name: 'sound', icon: 'mdi:volume-high', sortOrder: 50 },
          { name: 'tamper', icon: 'mdi:shield-off', sortOrder: 51 },
          { name: 'update', icon: 'mdi:update', sortOrder: 52 },
        ],
        icon: 'mdi:alert-circle'
      }
    };
    return entityConfig;
  }