name: Update Issue Template Versions

on:
  push:
    tags:
      - 'v*.*.*'   # löst aus, wenn ein neuer Tag wie v3.0.3 gepusht wird
  workflow_dispatch:   # optional: manuelles Starten über GitHub UI

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # alle Tags holen

      - name: Install yq (richtige Version)
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Get all tags
        id: get_tags
        run: |
          TAGS=$(git tag --sort=-v:refname | grep '^v' | sed 's/^v//' | jq -R -s -c 'split("\n")[:-1]')
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "Tags gefunden: $TAGS"

      - name: Update Issue Template
        run: |
          FILE=".github/ISSUE_TEMPLATE/bug_report.yml"
          echo "Updating $FILE with tags: $TAGS"

          # Schreibe die erkannten Tags in die Dropdown-Liste
          yq e '
            (.body[] | select(.id == "card_version").attributes.options) = (env(TAGS) | fromjson)
          ' -i "$FILE"

          # Bonus: zeige das Ergebnis im Log
          echo "Resulting options:"
          yq e '.body[] | select(.id == "card_version").attributes.options' "$FILE"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update issue template with latest tags"
          branch: main
