name: Update Issue Template Versions

on:
  push:
    tags:
      - 'v*.*.*'  # löst aus, wenn ein neuer Tag wie v3.0.3 gepusht wird
  workflow_dispatch:   # optional manuelles Starten

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout mit allen Tags
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Tags sammeln
      - name: Get all tags
        id: get_tags
        run: |
          TAGS=$(git tag --sort=-v:refname | grep '^v' | sed 's/^v//' | jq -R -s -c 'split("\n")[:-1]')
          if [ "$TAGS" = "[]" ] || [ -z "$TAGS" ]; then
            echo "⚠️ Keine Tags gefunden!"
          else
            echo "Tags found: $TAGS"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      # 3️⃣ Python-Skript: Issue Template updaten
      - name: Update Issue Template with Python
        env:
          TAGS: ${{ env.TAGS }}
        run: |
          python - <<'PY'
          import os, json, sys
          try:
              import yaml
          except ImportError:
              import subprocess
              subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "pyyaml"])
              import yaml

          TAGS_JSON = os.environ.get("TAGS", "[]")
          try:
              tags = json.loads(TAGS_JSON)
          except Exception as e:
              print("Error parsing TAGS JSON:", e)
              tags = []

          FILE = ".github/ISSUE_TEMPLATE/bug_report.yml"
          if not os.path.exists(FILE):
              print(f"Error: {FILE} not found")
              sys.exit(1)

          with open(FILE, "r", encoding="utf-8") as f:
              data = yaml.safe_load(f)

          if data is None:
              print("Error: YAML file empty or invalid")
              sys.exit(1)

          updated = False
          for item in data.get("body", []):
              if isinstance(item, dict) and item.get("id") == "card_version":
                  attrs = item.get("attributes") or {}
                  attrs["options"] = tags
                  item["attributes"] = attrs
                  if tags:
                      item["default"] = 0  # erster Eintrag als Default
                  updated = True
                  break

          if not updated:
              print("Warning: Kein Eintrag mit id 'card_version' gefunden.")
          else:
              with open(FILE, "w", encoding="utf-8") as f:
                  yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False)

              print("Successfully updated", FILE)
              for item in data.get("body", []):
                  if isinstance(item, dict) and item.get("id") == "card_version":
                      print("Resulting options:")
                      for v in item.get("attributes", {}).get("options", []):
                          print("-", v)
                      print("Default index:", item.get("default", "not set"))
                      break
          PY

      # 4️⃣ Zeige Diff für Kontrolle
      - name: Show diff
        run: |
          git --no-pager diff -- .github/ISSUE_TEMPLATE/bug_report.yml || true

      # 5️⃣ Commit + Push mit sicherem GITHUB_TOKEN
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update issue template with latest tags"
          branch: main
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
