name: Update Issue Template Versions

on:
  push:
    tags:
      - 'v*.*.*'  # löst aus, wenn ein neuer Tag wie v1.0.3 gepusht wird
  workflow_dispatch:   # optional, manuelles Starten

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Get all tags
        id: get_tags
        run: |
          TAGS=$(git tag --sort=-v:refname | grep '^v' | sed 's/^v//' | jq -R -s -c 'split("\n")[:-1]')
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Update Issue Template
        run: |
          FILE=".github/ISSUE_TEMPLATE/bug_report.yml"

          echo "Updating $FILE with tags: ${{ steps.get_tags.outputs.tags }}"

          yq -i '
            (.body[] | select(.id == "card_version").attributes.options) = 
            ( '${{ steps.get_tags.outputs.tags }}' | fromjson )
          ' "$FILE"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update issue template with latest tags"
          branch: main
